# Generated by Django 5.0.6 on 2024-06-25 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_profile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='verification_code',
        ),
    ]
