# Generated by Django 5.0.6 on 2024-06-08 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_review_user_name_review_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishing',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publishing',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='publisher_logos/'),
        ),
    ]
