# Generated by Django 5.0.6 on 2024-06-08 20:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_publishing_description_publishing_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
